# Generated by Django 3.2.9 on 2022-03-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name']},
        ),
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['-due_back']},
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.TextField(max_length=200),
        ),
    ]
